title: Stanislaus Stadlmann
description: My Personal Blog
author: Stanislaus Stadlmann
logo: /assets/bear_logo.png
github: https://github.com/Stan125
about: Student, M.Sc. Applied Statistics
disqus_shortname: aboutashu
google_analytics: UA-72862926-1
urls:
    - text: Home
      url: /
      icon: fa-home
      layout: post
    - text: About
      url: /about/
      icon: fa-comments
    - text: Projects
      url: /projects/
      icon: fa-desktop
    - text: Resume
      url: '#'
      icon: fa-graduation-cap
    - text: XML Feed
      url: /feed.xml
      icon: fa-feed
      target: _blank
      
social:
    - icon: fa-github
      link: https://github.com/Stan125
    - icon: fa-twitter
      link: 'https://twitter.com/stadlmann_'
    - icon: fa-linkedin
      link: 'https://de.linkedin.com/in/stanislaus-stadlmann-37779692'
    - icon: fa-stack-overflow
      link: 'http://stackoverflow.com/users/5052121/stan125'
    - icon: fa-xing
      link: https://www.xing.com/profile/Stanislaus_Stadlmann

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

url: "http://aboutashu.com/hcz-jekyll-blog"
baseurl: "/hcz-jekyll-blog"
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist